# Generated by Django 2.2 on 2019-05-20 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SomeControlType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='type')),
            ],
            options={
                'verbose_name': 'type',
                'verbose_name_plural': 'type',
            },
        ),
        migrations.CreateModel(
            name='SomeControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('body', models.TextField(verbose_name='text')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.SomeControlType', verbose_name='type')),
            ],
            options={
                'verbose_name': 'control1',
                'verbose_name_plural': 'control',
                'ordering': ['-create_time'],
            },
        ),
    ]
