# Generated by Django 2.2 on 2019-05-24 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='somecontrol',
            options={'ordering': ['-create_time'], 'verbose_name': 'control', 'verbose_name_plural': 'control'},
        ),
        migrations.CreateModel(
            name='SomeControlTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='name')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('refer', models.ManyToManyField(to='control.SomeControl')),
            ],
            options={
                'verbose_name': 'tags',
                'ordering': ['-create_time', 'owner'],
            },
        ),
    ]
