# Generated by Django 2.2 on 2019-05-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20190524_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='somecontrol',
            name='tags',
            field=models.ManyToManyField(to='control.SomeControlTags'),
        ),
    ]
