version: "3.4"
services:
  redis:
    image: redis:5.0
    volumes:
      - /data/redis/data:/data:z
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
    networks:
      - mynet
    deploy:
      resources:
        limits:
          memory: 1G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
      placement:
        constraints: [node.hostname == docker2]

  mysqld:
    image: mysql:8.0
    volumes:
    - /data/mysql/data:/var/lib/mysql:z
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
    - 3306:3306
    - 33060:33060
    networks:
    - mynet
    deploy:
      resources:
        limits:
          memory: 2G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
      placement:
        constraints: [node.hostname == docker]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOST=mysqld
    - PMA_PORT=3306
    ports:
    - 8001:80
    volumes:
    - /data/phpmyadmin/session:/sessions:z
    networks:
    - mynet
    deploy:
      resources:
        limits:
          memory: 1G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s


  admin:
    image: 192.168.1.120:5000/site_base_django:v0.2
    ports:
    - 8002:8002
    command: ./start.sh
    networks:
    - mynet
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 1G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    depends_on:
      - redis
      - mysqld

  nginx:
    image: nginx:latest
    ports:
    - 80:80
    - 8080:8080
    volumes:
    - ./docker/cfg/nginx/nginx-base.conf:/etc/nginx/nginx.conf:ro
    - ./docker/cfg/nginx/vhosts-swarm:/etc/nginx/conf.d:ro
    networks:
    - mynet
    deploy:
      resources:
        limits:
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 100
        window: 120s
      placement:
        constraints: [node.role == manager]
    depends_on:
      - admin
      - phpmyadmin


networks:
  mynet:
    external:
      name: proj1
