# Generated by Django 2.2 on 2019-05-24 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_somecontrol_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='somecontrol',
            name='tags',
        ),
    ]
